# Generated by Django 6.0 on 2025-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_running_time',
            field=models.DurationField(verbose_name='Хронометраж фильма'),
        ),
    ]
