# Generated by Django 6.0 on 2025-12-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_movie_running_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviehall',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='moviehall',
            name='movie_house',
        ),
        migrations.DeleteModel(
            name='MovieHouse',
        ),
    ]
