# Generated by Django 6.0 on 2025-12-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviehall',
            name='is_imax',
            field=models.BooleanField(default=False, verbose_name='IMAX'),
        ),
    ]
