# Generated by Django 6.0 on 2025-12-15 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_moviehall_is_imax'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='time_of_event',
            field=models.TimeField(default=datetime.time(19, 10, 55, 70313), verbose_name='Время проведения'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='date_of_event',
            field=models.DateField(default=datetime.date(2025, 12, 15), verbose_name='Дата проведения'),
        ),
    ]
