# Generated by Django 6.0 on 2025-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviesession_time_of_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='time_of_event',
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='date_of_event',
            field=models.DateTimeField(verbose_name='Дата и время проведения'),
        ),
    ]
